/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WriteRouteImport } from './routes/write'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardStoryIdRouteImport } from './routes/dashboard/$storyId'
import { Route as ReadPartIdRouteImport } from './routes/read/$partId'
import { Route as StoryStoryIdRouteImport } from './routes/story/$storyId'
import { Route as WriterHandleRouteImport } from './routes/writer/$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStoryIdRoute = DashboardStoryIdRouteImport.update({
  id: '/dashboard/$storyId',
  path: '/dashboard/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadPartIdRoute = ReadPartIdRouteImport.update({
  id: '/read/$partId',
  path: '/read/$partId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdRoute = StoryStoryIdRouteImport.update({
  id: '/story/$storyId',
  path: '/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterHandleRoute = WriterHandleRouteImport.update({
  id: '/writer/$handle',
  path: '/writer/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/write': typeof WriteRoute
  '/dashboard/$storyId': typeof DashboardStoryIdRoute
  '/read/$partId': typeof ReadPartIdRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/writer/$handle': typeof WriterHandleRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/write': typeof WriteRoute
  '/dashboard/$storyId': typeof DashboardStoryIdRoute
  '/read/$partId': typeof ReadPartIdRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/writer/$handle': typeof WriterHandleRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/write': typeof WriteRoute
  '/dashboard/$storyId': typeof DashboardStoryIdRoute
  '/read/$partId': typeof ReadPartIdRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/writer/$handle': typeof WriterHandleRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/profile'
    | '/sitemap.xml'
    | '/write'
    | '/dashboard/$storyId'
    | '/read/$partId'
    | '/story/$storyId'
    | '/writer/$handle'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/profile'
    | '/sitemap.xml'
    | '/write'
    | '/dashboard/$storyId'
    | '/read/$partId'
    | '/story/$storyId'
    | '/writer/$handle'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/browse'
    | '/profile'
    | '/sitemap.xml'
    | '/write'
    | '/dashboard/$storyId'
    | '/read/$partId'
    | '/story/$storyId'
    | '/writer/$handle'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WriteRoute: typeof WriteRoute
  DashboardStoryIdRoute: typeof DashboardStoryIdRoute
  ReadPartIdRoute: typeof ReadPartIdRoute
  StoryStoryIdRoute: typeof StoryStoryIdRoute
  WriterHandleRoute: typeof WriterHandleRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$storyId': {
      id: '/dashboard/$storyId'
      path: '/dashboard/$storyId'
      fullPath: '/dashboard/$storyId'
      preLoaderRoute: typeof DashboardStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$partId': {
      id: '/read/$partId'
      path: '/read/$partId'
      fullPath: '/read/$partId'
      preLoaderRoute: typeof ReadPartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId': {
      id: '/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/story/$storyId'
      preLoaderRoute: typeof StoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/$handle': {
      id: '/writer/$handle'
      path: '/writer/$handle'
      fullPath: '/writer/$handle'
      preLoaderRoute: typeof WriterHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WriteRoute: WriteRoute,
  DashboardStoryIdRoute: DashboardStoryIdRoute,
  ReadPartIdRoute: ReadPartIdRoute,
  StoryStoryIdRoute: StoryStoryIdRoute,
  WriterHandleRoute: WriterHandleRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
